version: "3.8"

services:
  app:
    image: image:latest
    container_name: test
    restart: always
    env_file:
      - .env
    volumes:
      - app_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.mondomaine.com`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=le"
    networks:
      - proxy

volumes:
  app_data:

networks:
  proxy:
    external: true

